Vagrant.configure(2) do |config|

(1..3).each do |i|
  config.vm.define "node-#{i}" do |node|
    node.vm.box = "puppetlabs/debian-7.6-64-puppet"
    node.vm.hostname = "node-#{i}"
    node.vm.network "private_network", ip: "172.16.0.#{i}"

    node.vm.provision "puppet" do |puppet|
    puppet.module_path = "modules"
    end

  end
end
end